#!/bin/bash
#File: load_asns_secure
#Author: lxw
#Time: 2015-12-01

if [ $# -lt 1 ]
then
    echo "Usage: load_asns_secure -i apnic file.csv"
    exit 0
"""
else
    echo $0
    echo $1
    echo $2
    echo $3
"""
fi

./preCheckASN.py $1 $2 $3

if [ $? -eq 0 ]
then
    echo "0"
else
    echo "1"
fi
